language: node_js

install:
  - npm install
  # I don't want changes to package-lock.json to show up as local git
  - git checkout package-lock.json

script:
  - npm run lint
  - npm run build

after_success:
  - npm run lh -- https://akabakibi.com/